### PR TITLE
Sree

### PR DESCRIPTION
**Pull request by sreekarpeddi**
Created Pull request to be reviewed by Developers @christopher-eddy-state-ca-gov  @Thuy-Ly  @ssiwan 

Improved encryption 
Replace the deprecated encryption method with a recommended method by changing the mode of the AesManaged AES symmetric algorithm implementation from CBC to GCM.

### CODE REVIEW

**Comment by sreekarpeddi** [comment]
@SaraAhmad944  Please check

**Comment by sreekarpeddi** [comment]
@christopher-eddy-state-ca-gov  Please check

**Comment by christopher-eddy-state-ca-gov** [comment]
Trying merge

**Review by christopher-eddy-state-ca-gov — APPROVED** [review]
Looks good

**Review by NadiaSham — APPROVED** [review]
Approved. Looks good.

**Review by ssiwan — APPROVED** [review]
The team fixed a Sec Vulnerability "AES-CBC to AES-GCM" - Pushing and merging out to the public branch

**Pull request merged**
